### ISSUE TITLE
Playing sound files on click

### ISSUE THREAD

**Issue by dusannikolic92** [pwdonh/audio_ratings#1]
Hello Peter, 

Thank you for this lovely toolbox!

I would like to be able to play files on click instead on hover. Since I will have my participants drag and drop at least 20 audio files, it becomes overwhelming that, after each hover, the file is being played. 

Can it be done?

Best,
Dusan

**Comment by pwdonh** [comment]
Hi Dusan, now I get what you mean. Is it mostly about accidentally hovering over tokens which triggers a sound every time? I can see that it can be annoying. I might add this as an option soon (disable playback on hover), since a reviewer had also mentioned this.

**Comment by dusannikolic92** [comment]
Yes, mostly because it triggers the sound every time you hover over and drag it, so it can get distracting. If you make sounds play on click, I will use it right away because it is a great toolbox (and because I also need it soon).

**Comment by pwdonh** [comment]
Hi Dusan, I didn't come back to you, sorry. I had tried to implement this back in January but the click events didn't work well. Did you find some workaround for your experiment?

**Comment by dusannikolic92** [comment]
Hello Peter,

I did not really solve it. I found a workaround it. E.g. I have a recording that has the same word with pauses in between. This means that the word such as 'hello' will not be constantly repeated whenever one hovers over with a cursor, but the user will have to wait a second for the word to be uttered. This is, I believe, less distracting. 

Also, I am trying to host and save the data on my server. If you have any suggestions on how to do this with your experiment, that would be great.

**Comment by pwdonh** [comment]
OK. 

Have you also tried to set the option `loop: false`: this way the sound file will only be played once when you hover.

Also I did add a mute key. You can try it out by setting the option `mute_key: 's'`: this way you can turn on/off sound by pressing 's'. I'm not sure it's very useful, that's why I didn't document it so far. Let me know.

As for hosting the experiment, this is a good list: https://www.jspsych.org/7.2/overview/running-experiments/#hosting-the-experiment-and-saving-the-data

**Comment by dusannikolic92** [comment]
Hi Peter,

Yes! These two work like a charm. Thank you!

**Comment by pwdonh** [comment]
Happy to hear



-------- Original message --------
From: dusannikolic92 ***@***.***>
Date: 2022-05-05 12:41 a.m. (GMT+01:00)
To: pwdonh/audio_tokens ***@***.***>
Cc: "Donhauser, Peter" ***@***.***>, Comment ***@***.***>
Subject: Re: [pwdonh/audio_tokens] Playing sound files on click (Issue #1)


Hi Peter,

Yes! These two work like a charm. Thank you!
