### ISSUE TITLE
Data visualization

### ISSUE THREAD

**Issue by dusannikolic92** [pwdonh/audio_ratings#4]
Hi Peter,

I am running the experiment currently on Cognition.run, and when I receive the data from the experiment, there are what appears to be coordinates to where the participants placed the circles. Can you tell me how I can re-create their response? How can I visualize the responses and interpret the coordinates? I know it's a big question, but any hint would be quite helpful.

**Comment by pwdonh** [comment]
What type of rating are you doing? The free placement of tokens in a circle (similarity)?



-------- Original message --------
From: dusannikolic92 ***@***.***>
Date: 2022-05-05 12:43 a.m. (GMT+01:00)
To: pwdonh/audio_tokens ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pwdonh/audio_tokens] Data visualization (Issue #4)


Hi Peter,

I am running the experiment currently on Cognition.run, and when I receive the data from the experiment, there are what appears to be coordinates to where the participants placed the circles. Can you tell me how I can re-create their response? How can I visualize the responses and interpret the coordinates? I know it's a big question, but any hint would be quite helpful.

**Comment by pwdonh** [comment]
If that's the case, this is what you need to interpret the coordinates: 

The arena where the tokens can be placed is a circle with radius 0.5

The values you get in the results are [x, y] coordinates. [0, 0] will be the center of the circle, [-0.5, 0] e.g. will be the leftmost coordinate that you can place a token, [0.5, 0] the rightmost, etc. This means that the maximum distance between two tokens is 1. So interpretation for the distances is: 0=most similar, 1=most dissimilar.

This information is missing so far, thanks for bringing it up.

**Comment by dusannikolic92** [comment]
Yes, it is the free placement, but the rating type is 'cluster'. What I received from one participant were the following ratings: [1,1,1,2,1,1,1,1], and elapsed [26.047182141883425,25.445094182076836,15.503455501815061,25.823949135860587,12.147566917150098,20.42711552700361,15.191530785560367,21.067418345252083]; 

I also have a feature2d trial (2 dimensions) and the ratings are: 
[[0.09230769230769231,0.9230769230769231],[0.8543956043956044,0.7769230769230769],[0.08956043956043959,0.1076923076923077],[0.7131868131868132,0.1],[0.7483516483516484,0.7730769230769231],[0.948901098901099,0.7730769230769231],[0.17252747252747266,0.1],[0.926923076923077,0.9153846153846154]]

How should I interpret these two types of ratings?

**Comment by pwdonh** [comment]
Have you checked the analysis folder in the repository. I've added it more recently:

https://github.com/pwdonh/audio_tokens/tree/main/analysis

The rating type 'cluster' implements a categorical rating, so in this example [1,1,1,2,1,1,1,1] the participant decided to group them in two clusters, one of them only containing a single item.

For feature2d you rate along two defined dimensions (whatever you labeled them), and the results give you the associated ratings from 0 to 1 (interpreted as whatever you put as 'anchor'). In your example, the first item was rated 0.092 on the first dimension and 0.92 on the second dimension

**Comment by dusannikolic92** [comment]
Great, this helps a lot and the code is really neat!
