### ISSUE TITLE
How to have instructions displayed during the trial?

### ISSUE THREAD

**Issue by dusannikolic92** [pwdonh/audio_ratings#5]
Hello Peter,

I would like to know whether I can have some instructions displayed during the trial? I would like to have instructions while participants are moving the recordings around in the circle.
Can this be done?

Thank you!

-Dusan

**Comment by pwdonh** [comment]
Yes, that makes sense to have. I added a parameter 'prompt' that works like in other jsPsych plugins (https://www.jspsych.org/7.2/plugins/image-button-response/)
