### ISSUE TITLE
Feature rating anchor text

### ISSUE THREAD

**Issue by mhhenry** [pwdonh/audio_ratings#7]
Hi Peter,

I ran into an issue with the multi-feature rating. When I only have one talker per trial (which I want), the last feature rating anchors get cut off at the bottom, making the text difficult to read. Is there a workaround for this? I tried adjusting the font size for anchors in the audio-tokens.js file which didn't affect anything. 

<img width="443" alt="Screenshot 2023-04-03 at 10 38 22 PM" src="https://user-images.githubusercontent.com/121317290/229672899-a57f0591-ee8f-4194-ab29-e6f5212113ec.png">

This issue is also happening on single-feature rating with one talker:

<img width="374" alt="Screenshot 2023-04-03 at 10 54 21 PM" src="https://user-images.githubusercontent.com/121317290/229675046-a32e56e8-bc15-4952-960c-0667a503c11e.png">

Thanks for your help on this!

Malachi

**Comment by mhhenry** [comment]
I figured it out! I needed to change vanchor argument in the audio-tokens.js file!

**Comment by pwdonh** [comment]
Glad it worked. Does it look OK if you change the vanchor?

It seems that the height of the svg is not specified well. It's done somewhat poorly here, something that can be improved:

https://github.com/pwdonh/audio_tokens/blob/1703a7e58c97b2fad5c45b99d251cb7d38f0bba2/js/jspsych-audio-tokens-v7.js#L86
